### ISSUE TITLE
Could not compile for ESP32 on platformio

### ISSUE THREAD

**Issue by GiPe66** [yeganemehr/cpp-promise#1]
In file included from src/main.cpp:2:
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:39:44: error: 'vector' in namespace 'std' does not name a template type
  static Promise<void> *sequence(const std::vector<std::function<Promise<void> *()>> &funcs);
                                            ^~~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:39:39: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:1:1:
+#include <vector>
 #ifndef PROMISE_HPP
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:39:39:
  static Promise<void> *sequence(const std::vector<std::function<Promise<void> *()>> &funcs);
                                       ^~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:39:50: error: expected ',' or '...' before '<' token
  static Promise<void> *sequence(const std::vector<std::function<Promise<void> *()>> &funcs);
                                                  ^
src/main.cpp: In lambda function:
src/main.cpp:12:25: error: 'class EspClass' has no member named 'random'
   uint32_t result = ESP.random();
                         ^~~~~~
*** [.pio\build\wemos_d1_mini32\src\main.cpp.o] Error 1
In file included from .pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:1:
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:39:44: error: 'vector' in namespace 'std' does not name a template type
  static Promise<void> *sequence(const std::vector<std::function<Promise<void> *()>> &funcs);
                                            ^~~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:39:39: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:5:1:
+#include <vector>
 #include <exception>
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:39:39:
  static Promise<void> *sequence(const std::vector<std::function<Promise<void> *()>> &funcs);
                                       ^~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:39:50: error: expected ',' or '...' before '<' token
  static Promise<void> *sequence(const std::vector<std::function<Promise<void> *()>> &funcs);
                                                  ^
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:9:38: error: 'vector' in namespace 'std' does not name a template type
 void callNextPromiseInSeq(const std::vector<std::function<Promise<void> *()>> &funcs, size_t *index, Promise<void> *promise)
                                      ^~~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:9:33: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:2:1:
+#include <vector>

.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:9:33:
 void callNextPromiseInSeq(const std::vector<std::function<Promise<void> *()>> &funcs, size_t *index, Promise<void> *promise)
                                 ^~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:9:44: error: expected ',' or '...' before '<' token
 void callNextPromiseInSeq(const std::vector<std::function<Promise<void> *()>> &funcs, size_t *index, Promise<void> *promise)
                                            ^
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp: In function 'void callNextPromiseInSeq(int)':
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:11:8: error: 'index' was not declared in this scope
  if ((*index) == funcs.size())
        ^~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:11:18: error: 'funcs' was not declared in this scope
  if ((*index) == funcs.size())
                  ^~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:13:10: error: type '<type error>' argument given to 'delete', expected pointer
   delete index;
          ^~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:14:3: error: 'promise' was not declared in this scope
   promise->resolve();
   ^~~~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:14:3: note: suggested alternative: 'Promise'
   promise->resolve();
   ^~~~~~~
   Promise
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:17:21: error: 'funcs' was not declared in this scope
  Promise<void> *p = funcs[(*index)++]();
                     ^~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:17:29: error: 'index' was not declared in this scope
  Promise<void> *p = funcs[(*index)++]();
                             ^~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:19:62: error: 'promise' was not declared in this scope
  p->onSuccess(std::bind(&callNextPromiseInSeq, funcs, index, promise));
                                                              ^~~~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:19:62: note: suggested alternative: 'Promise'
  p->onSuccess(std::bind(&callNextPromiseInSeq, funcs, index, promise));
                                                              ^~~~~~~
                                                              Promise
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp: At global scope:
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:23:51: error: 'vector' in namespace 'std' does not name a template type
 Promise<void> *Promise<void>::sequence(const std::vector<std::function<Promise<void> *()>> &funcs)
                                                   ^~~~~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:23:46: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
 Promise<void> *Promise<void>::sequence(const std::vector<std::function<Promise<void> *()>> &funcs)
                                              ^~~
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:23:57: error: expected ',' or '...' before '<' token
 Promise<void> *Promise<void>::sequence(const std::vector<std::function<Promise<void> *()>> &funcs)
                                                         ^
In file included from c:\users\jpr\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\sys-include\sys\reent.h:503,
                 from C:/Users/jpr/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/newlib/platform_include/sys/reent.h:17,
                 from c:\users\jpr\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\sys-include\wchar.h:6,
                 from c:\users\jpr\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\include\c++\8.4.0\cwchar:44,
                 from c:\users\jpr\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\include\c++\8.4.0\bits\postypes.h:40,
                 from c:\users\jpr\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\include\c++\8.4.0\bits\char_traits.h:40,
                 from c:\users\jpr\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\include\c++\8.4.0\string:40,
                 from c:\users\jpr\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\include\c++\8.4.0\stdexcept:39,
                 from c:\users\jpr\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\include\c++\8.4.0\array:39,
                 from c:\users\jpr\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\include\c++\8.4.0\tuple:39,
                 from c:\users\jpr\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\include\c++\8.4.0\functional:54,
                 from .pio/libdeps/wemos_d1_mini32/promise/src/Promise.hpp:4,
                 from .pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:1:
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp: In static member function 'static Promise<void>* Promise<void>::sequence(int)':
.pio/libdeps/wemos_d1_mini32/promise/src/Promise.cpp:25:10: error: 'funcs' was not declared in this scope
  assert(!funcs.empty());

**Comment by yeganemehr** [comment]
Hi @GiPe66 
I'll look into it today or tomorrow and let you know my results.

**Comment by yeganemehr** [comment]
@GiPe66 I released a new version that patched the problem.

**Comment by GiPe66** [comment]
Many thanks. I will test it next week.
